### ISSUE TITLE
Log debug messages to standard error

### ISSUE THREAD

**Issue by suriya** [Stranger6667/postmarker#102]
Postmarker by default logs debug messages to [standard output](https://github.com/Stranger6667/postmarker/blob/25607368e02ca63c62c8efc31614d9d258152840/postmarker/logging.py#L23). It would be better if these messages go to standard error, or there is an option to specify the same.

**Comment by Stranger6667** [comment]
Now the default output stream is ``sys.strerr`` - the same as in ``logging.StreamHandler``.
Thank you for the report :)

**Comment by suriya** [comment]
Thank you once again!

**Comment by Stranger6667** [comment]
You're very welcome! :)
The new release (0.8.0) is already on PyPI
