### ISSUE TITLE
missing dependency on mock

### ISSUE THREAD

**Issue by hmoffatt** [Stranger6667/postmarker#145]
postmarker requires mock to be installed (in python 2.7), but it doesn't declare this.

> [11:32AM] hamish@quokka:~/dev/postmark $ virtualenv py
> New python executable in py/bin/python
> Installing setuptools, pip...done.
> [11:32AM] hamish@quokka:~/dev/postmark $ py/bin/pip install postmarker
> Downloading/unpacking postmarker
>   Downloading postmarker-0.11.2-py2.py3-none-any.whl
> Downloading/unpacking requests (from postmarker)
>   Downloading requests-2.18.4-py2.py3-none-any.whl (88kB): 88kB downloaded
> Downloading/unpacking certifi>=2017.4.17 (from requests->postmarker)
>   Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB): 330kB downloaded
> Downloading/unpacking idna>=2.5,<2.7 (from requests->postmarker)
>   Downloading idna-2.6-py2.py3-none-any.whl (56kB): 56kB downloaded
> Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests->postmarker)
>   Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
> Downloading/unpacking urllib3>=1.21.1,<1.23 (from requests->postmarker)
>   Downloading urllib3-1.22-py2.py3-none-any.whl (132kB): 132kB downloaded
> Installing collected packages: postmarker, requests, certifi, idna, chardet, urllib3
> Successfully installed postmarker requests certifi idna chardet urllib3
> Cleaning up...
> [11:32AM] hamish@quokka:~/dev/postmark $ py/bin/python
> Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
> [GCC 6.3.0 20170118] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from postmarker.core import PostmarkClient
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hamish/dev/postmark/py/local/lib/python2.7/site-packages/postmarker/core.py", line 5, in <module>
>     from ._compat import get_args, urljoin
>   File "/home/hamish/dev/postmark/py/local/lib/python2.7/site-packages/postmarker/_compat.py", line 13, in <module>
>     from mock import patch  # noqa
> ImportError: No module named mock
> >>> 
> >>> 
>

**Comment by Stranger6667** [comment]
Hi @hmoffatt !
Thank you for the report, I'll make a bugfix release today.

Kind Regards

**Comment by Stranger6667** [comment]
New release is on PyPI
