### ISSUE TITLE
TemplateAlias not supported

### ISSUE THREAD

**Issue by AarneHuttunen** [Stranger6667/postmarker#150]
Hi!

Just wanted to inform you (if you didn't know already) that Postmark supports [template aliases](https://postmarkapp.com/support/article/1100-templates-faq)

I'd guess this can be easily implemented. The aliases make the code more readable and offer nifty ways to have some logic in the server backend.

So instead of
`postmark.emails.send_with_template(
	    TemplateId=123456,
	    TemplateModel=email_data,
	    From='example@example.com',
	    To=email_addresses
	)`

You could do
`postmark.emails.send_with_template(
	    TemplateAlias="welcome-email"
	    TemplateModel=email_data,
	    From='example@example.com',
	    To=email_addresses
	)`

**Comment by Stranger6667** [comment]
Hi @AarneHuttunen !
Thank you for the information! I'll work on it this weekend :)
