### ISSUE TITLE
Remove dependency on mock

### ISSUE THREAD

**Issue by suriya** [Stranger6667/postmarker#158]
Postmarker has a dependency on `mock`, used here: https://github.com/Stranger6667/postmarker/blob/c0c0f7af623dc7b3fc0c030867773755dca31f67/postmarker/_compat.py#L13

I notice that `mock.patch` is used only in tests. Does this make sense to move the line to a separate file `_compat_tests.py` so that normal usage of `postmarker` does not need the `mock` package?

**Comment by Stranger6667** [comment]
Hi @suriya!
Sorry for not getting back to you.
This code is used in `pytest` integration, which is a part of the distribution. Thus it can't be moved to another place.

**Comment by Stranger6667** [comment]
I completely agree with your motivation. The possible solution is to move `mock` to extras. For production, you could install `postmarker` and for your tests, you could install `postmarker[testing]` instead. What do you think?

**Comment by suriya** [comment]
My suggestion is simpler. Create a file called `_compat_tests.py` and import mock in that file. In production, that file will not be used.

**Comment by suriya** [comment]
@Stranger6667 Could you help with this issue?

**Comment by Stranger6667** [comment]
Should be fixed now. In a case of any issues, feel free to reopen it

**Comment by suriya** [comment]
Thank you so much!
