### ISSUE TITLE
Having trouble with international characters in local segment of email address

### ISSUE THREAD

**Issue by scottrmercer** [Stranger6667/postmarker#178]
When trying to send to an email address with unicode characters, I get an error back from postmark. 

postmarker.exceptions.ClientError: [300] Error parsing 'To': Illegal email mailbox 'rafał' in address 'rafał@xxxxxx.com'.

I'm experimenting to find a workaround, as it is not clear whether this is a bug or a problem with our implementation.

**Comment by Stranger6667** [comment]
Hej @scottrmercer !
I believe it should be encoded before sending, I’ll take a look soon - we can have it on the postmarker side, and as a quick workaround you could try to encode it manually before sending

**Comment by scottrmercer** [comment]
Thanks for the quick response. I got this back from Postmark:

> We do not have support for unicode characters in recipient addresses at this time, unfortunately. We do plan on adding support for them down the road though. 
> 
> I have added your information to the feature request we have tracking adding support for unicode recipient addresses and will let you know when you can send to addresses with unicode characters. For now, you would need to send to recipient addresses with unicode characters in them using another service.
