### ISSUE TITLE
send_with_template won't allow alias

### ISSUE THREAD

**Issue by 2x2xplz** [Stranger6667/postmarker#179]
Referring to #150 

When I try to send an email using a template alias, 
`postmark.emails.send_with_template(TemplateAlias=alias, TemplateModel=model, To=sendto, From=efrom)`

I get the following response:
`TypeError: send_with_template() missing 1 required positional argument: 'TemplateId'`

Thanks.

**Comment by viperfx** [comment]
@Stranger6667 I am facing this issue too.

From the Postmark API specs - https://postmarkapp.com/developer/api/templates-api#email-with-template

> TemplateAlias  - The alias of a template to use when sending this message. Required if TemplateID is not specified.
> TemplateId - The template to use when sending this message. Required if TemplateAlias is not specified.

**Comment by romatallinn** [comment]
@Stranger6667 any updates on this one?

**Comment by Stranger6667** [comment]
Hi @romatallinn 

Sorry, I completely missed this issue; I will put it on my TODO list for the next week. Thank you for pinging me

**Comment by Stranger6667** [comment]
The fix is released in `0.17.0` (it also drops support for Python 3.5).
