### ISSUE TITLE
Documentation is outdated on ReadTheDocs

### ISSUE THREAD

**Issue by loicteixeira** [Stranger6667/postmarker#195]
Unfortunately the docs at https://postmarker.readthedocs.io/en/stable/ are stuck on 1.3.0.

Looking at the changes since then (see https://github.com/Stranger6667/postmarker/compare/0.13.0...v0.17.1), I'm not too sure what could have caused this, but I know RTD to be quite picky about docs dependencies, so maybe the move to `pyproject.toml`?

**Comment by Stranger6667** [comment]
Yep, their site says the following:

> Your project, Postmarker, needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations.

I will take a look :)

**Comment by Stranger6667** [comment]
The docs are updated! Thank you for reporting it :)

**Comment by loicteixeira** [comment]
Awesome. Thank you for the great project 👍

**Comment by Stranger6667** [comment]
You're very welcome! :)
