### ISSUE TITLE
Django 4.0 incompatibilities

### ISSUE THREAD

**Issue by robshep** [Stranger6667/postmarker#200]
Django release 4.0 has introduced some incompatibilities but they are all quite benign.  

1. django/utils/encoding#force_text has been removed. It was previously deprecated.

`force_str` can be used as a direct replacement and was aliased.  Available since Feb 2019
https://github.com/django/django/commit/3bb6a4390c0a57da991fcb1c0642b9b3fccff751

`force_text` was deprecated shortly after in 
https://github.com/django/django/commit/d55e88292723764a16f0689c73bc7e739dfa6047

`force_text` was then removed in the v4 release cycle as per the deprecation notice
https://github.com/django/django/commit/810f037b29402f848a766f6900b4ebfbaf64cc88

2. `Signal` has lost the `provided_args` initialiser argument

This argument was deprecated in Mar 2020 at
https://github.com/django/django/commit/769cee525222bb155735aba31d6174d73c271f3c

And subsequently removed in Jan 2021 at https://github.com/django/django/commit/1adcf20385c2856d3655089ff7a0b55b32e5587a

I don't know which previous versions of Django this affects or how backwards compatible you want to be, but I'll post a RP with these changes to run through Django v4.0

**Comment by robshep** [comment]
https://github.com/Stranger6667/postmarker/pull/201

**Comment by Stranger6667** [comment]
Hi @robshep,

Thank you for opening this issue :) There is no explicit Django support policy, but I think it will be reasonable to support only versions that are [officially supported](https://www.djangoproject.com/download/) by the Django community - 2.2, 3.2, and 4.0.

**Comment by Stranger6667** [comment]
Resolved via #201 

I added a few more test builds to ensure compatibility with Django 2.2, 3.2, and 4.0. The changes will be available in the upcoming 1.0 release in a few minutes
