### ISSUE TITLE
Send Tag information via the Django interface

### ISSUE THREAD

**Issue by jdotjdot** [Stranger6667/postmarker#59]
I can't figure out a way to send `Tag` information to Postmark when using the Django `EmailBackend`. I did dive deep into the code but unfortunately had difficulty figuring out where the right place even to patch it would be.

I know I could use the regular `PostmarkClient`, but it's important for us to continue using the built-in Django mechanism so that we can stay vendor agnostic.

Can you point me in the right direction on where a patch would go?

**Comment by Stranger6667** [comment]
Hello, @jdotjdot !

Can I ask you how you add tags to messages? Do you want to send different tags for different messages of mark them all with a single tag? And how would you send messages - ``send_mail``, ``get_connection`` or ``message.send()``?

There are a few options to work with tags.

1. Use ``get_connection`` to pass ``Tag`` information to ``EmailBackend`` instantiation. And update ``send_messages`` accordingly. Something like this:

```python
class EmailBackend(BaseEmailBackend):

    def __init__(self, token=None, fail_silently=False, tag=None, **kwargs):
        super(EmailBackend, self).__init__(fail_silently=fail_silently)
        self.tag = tag
    ...
    def send_messages(self, email_messages):
        ...
        response = self.client.emails.send_batch(*prepared_messages, TrackOpens=self.get_option('TRACK_OPENS'), Tag=self.tag)
        ...
```
2. Global tag value. The same implementation as ``TRACK_OPENS``
3. Modify email message. You're able to attach tag to email instance as an attribute. Default ``django.core.mail.send_mail`` doesn't allow any extra arguments, thus you can do the following.

```python
from django.core import mail

message = mail.EmailMessage(
    'Subject', 'Body', 'sender@example.com', ['receiver@example.com']
)
message.tag = 'Tag value'
message.send()
```

Django uses ``SafeMIMEText`` internally, thus tag should be attached to the message instance.

postmarker/django.py
```python

    def send_messages(self, email_messages):
        ...
        prepared_messages = [self.prepare_message(message) for message in email_messages]
        ...

    def prepare_message(self, message):
        instance = message.message()
        instance.tag = getattr(message, 'tag', None)
        return instance
```


postmarker/models/email.py
```python

class Email(BaseEmail):

    ...

    @classmethod
    def from_mime(cls, message, manager):
        ...
        tag = getattr(message, 'tag', None)
        return cls(manager=manager, From=sender, To=to, TextBody=text, HtmlBody=html, Subject=subject, Cc=cc, Bcc=bcc,
                   ReplyTo=reply_to, Attachments=attachments, Tag=tag)
```

I hope, that this thought will help :)

**Comment by jdotjdot** [comment]
I looked at the `Email` model, but the issue is we use `EmailMultiAlternatives`, which seems to be a Django class rather than a postmarker one we could override. 

We typically set up a single `EmailMultiAlternatives` instance and then call `email.send()`, and that's it.  We don't do any batch emailing that way. I'd prefer to have multiple tags per email if possible, but I think Postmark only supports one tag per email. Different emails would get different tags, so global setting wouldn't work.

Thoughts?

**Comment by Stranger6667** [comment]
In this case postmarker's Django backend works similar to ``django.code.mail.backends.smtp.EmailBackend`` (the following code is taken from this class):

```python
    def _send(self, email_message):
        # preparation 
        message = email_message.message()
        # sending with exceptions catching
```

Here, the `message` method transforms Django's ``EmailMessage`` / ``EmailMultiAlternatives`` to ``SafeMIMEText`` (an extension of ``email.mime.text.MIMEText``).
After that, message is send via concrete backend methods. In case of postmarker via ``PostmarkClient.emails.send_batch`` method.

This method works well with default Python email entities (as ``MIMEText``, ``MIMEMultipart``, etc). Basically this method converts given instances to postmarker's ``Email`` instances via ``Email.from_mime`` method.

So, I can propose to do this - create a new class, derived from Django's ``EmailMultiAlternatives`` and set ``tag`` attribute:

Python 3-only compatible example:

```python
class TaggedEmailMultiAlternatives(EmailMultiAlternatives):

    def __init__(self, *args, tag=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.tag = tag
```

After that I can implement 3rd option from my first comment and add it to the next release.

Or I can do both - add a mixin/class, which will provide such features out of the box. Probably it would be better option. In the same way it would be possible to add some more postmark-only features to Django email messages - like per-message TrackOpens or TrackLinks.

**Comment by Stranger6667** [comment]
Done! Version 0.5.3 has ``PostmarkEmailMultiAlternatives``,  ``PostmarkEmailMessage``. You can use them instead of Django's.

Example:

```python
>>> from postmarker.django import PostmarkEmailMessage
>>> PostmarkEmailMessage(
    'Subject', 'Body', 'sender@example.com', ['receiver@example.com'],
    tag='Test tag'
).send()
```

Or you can use ``PostmarkEmailMixin`` for your own classes

**Comment by Stranger6667** [comment]
Hello, @jdotjdot !

Does it help?

**Comment by jdotjdot** [comment]
You rock!  Sorry, hadn't seen the update until you just bumped it now.

Looks great.  Thanks so much for your support on this. I'm just waiting for Postmark to fix a bug on their end with disabling track opens, and then I'll put `postmarker` right back in the project and let you know!

**Comment by Stranger6667** [comment]
Thank you! You're very welcome :)

**Comment by jdotjdot** [comment]
This is working great, thanks! Using it in production now.
