### ISSUE TITLE
Accept verbosity option while creating Django backend

### ISSUE THREAD

**Issue by suriya** [Stranger6667/postmarker#92]
`PostmarkClient` accepts a `verbosity` option. However, there is no way to specify this option when using the Django backend. My workaround is to add a `VERBOSITY` field in `settings.POSTMARK` and use this field's value in my custom backend. It would be good to have this functionality in `postmarker`.

```python
from postmarker.core import PostmarkClient
from postmarker.django import EmailBackend as PostmarkerDjangoEmailBackend

class EmailBackend(PostmarkerDjangoEmailBackend):
    def open(self):
        if self.client is None:
            verbosity = self.get_option('VERBOSITY') or 0
            self.client = PostmarkClient(token=self.token, verbosity=verbosity)
        return False
```

**Comment by Stranger6667** [comment]
Thank you for the proposal! It is now merged in #93
